import { Container, Grid, List, Space, Stack, Text } from "@mantine/core";

export function PrivacyPolicy() {
    return (
        <>
            <Container size="lg" c="#dcdcdc" mt="xl">
                <Stack>
                    <Text size="50px">Privacy Policy</Text>
                    <Text>Updated MM-DD-YYYY</Text>
                    <Text>
                        [NAME] (“we,” “our,” or “us”) is committed to protecting your privacy.
                        This Privacy Policy explains how your personal information is collected, used, and disclosed by [NAME].
                    </Text>
                    <Text>
                        This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, [NAME].
                        By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                    </Text>

                    <Space h="lg" />

                    <Text size="30px">Definitions and key terms</Text>
                    <Text>
                        To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
                    </Text>
                    <List>
                        <List.Item>[ Cookie ] small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.</List.Item>
                        <List.Item>[ Company ] when this policy mentions “Company,” “we,” “us,” or “our,” it refers to [NAME]. That is responsible for your information under this Privacy Policy.</List.Item>
                        <List.Item>[ Country ] where [NAME] or the owners/founders of [NAME] are based, in this case is Canada.</List.Item>
                        <List.Item>[ Customer ] refers to the company, organization or person that signs up to use the [NAME] Service to manage the relationships with your consumers or service users.</List.Item>
                        <List.Item>[ Device ] any internet connected device such as a phone, tablet, computer or any other device that can be used to visit [NAME] and use the services.</List.Item>
                        <List.Item>[ IP address ] Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</List.Item>
                        <List.Item>[ Personnel ] refers to those individuals who are employed by [NAME] or are under contract to perform a service on behalf of one of the parties.</List.Item>
                        <List.Item>[ Personal Data ] any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</List.Item>
                        <List.Item>[ Service ] refers to the service provided by [NAME] as described in the relative terms (if available) and on this platform.</List.Item>
                        <List.Item>[ Third-party service ] refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</List.Item>
                        <List.Item>[ Website ] [NAME]'s site, which can be accessed via this URL: VerifiedHours.com</List.Item>
                        <List.Item>[ You ] a person or entity that is registered with [NAME] to use the Services.</List.Item>
                    </List>

                    <Space h="lg" />

                    <Text size="30px">What Information Do We Collect?</Text>
                    <Text>We only collect the information that you provide to us. This is true when you register on our site, register for a subscription plan, subscribe to our newsletter, join a waitlist, responding to a survey or filling out a form.</Text>
                    {/* <List>
                        <List.Item>Name / Username</List.Item>
                        <List.Item>Cell number</List.Item>
                        <List.Item>Work number (optional)</List.Item>
                        <List.Item>Home number (optional)</List.Item>
                        <List.Item>Street address</List.Item>
                        <List.Item>Country</List.Item>
                        <List.Item>City</List.Item>
                        <List.Item>Province/state</List.Item>
                        <List.Item>Postal code</List.Item>
                        <List.Item>Gender</List.Item>
                        <List.Item>Date of birth</List.Item>
                        <List.Item>Allergies (optional)</List.Item>
                        <List.Item>Email addresses</List.Item>
                        <List.Item>Billing addresses</List.Item>
                        <List.Item>Debit/credit card numbers</List.Item>
                        <List.Item>Password</List.Item>
                    </List> */}

                    <Space h="lg" />

                    <Text size="30px">How Do We Use The Information We Collect?</Text>
                    <Text>Any of the information we collect from you may be used in one of the following ways:</Text>
                    <List>
                        <List.Item>To personalize your experience (your information helps us to better respond to your individual needs)</List.Item>
                        <List.Item>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</List.Item>
                        <List.Item>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</List.Item>
                        <List.Item>To process transactions</List.Item>
                        <List.Item>To administer a contest, promotion, survey or other site feature</List.Item>
                        <List.Item>To send periodic emails</List.Item>
                    </List>

                    <Space h="lg" />

                    <Text size="30px">When does [NAME] use end user information from third parties?</Text>
                    <Text>[NAME] will collect End User Data necessary to provide the [NAME] services to our customers.</Text>
                    <Text>End users may voluntarily provide us with information they have entered into the various forms in our service.</Text>

                    <Space h="lg" />

                    <Text size="30px">Do we share the information we collect with third parties?</Text>
                    <Text>
                        We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
                        We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
                    </Text>
                    <Text>
                        We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website.
                        We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
                    </Text>
                    <Text>
                        We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the website in a shared location, and type of the device used to visit the website.
                        They may aggregate information about our advertising and what you see on the website and then provide auditing, research and reporting for us and our advertisers. We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.
                    </Text>

                    <Space h="lg" />

                    <Text size="30px">Where and when is information collected from customers and end users?</Text>
                    <Text>[NAME] will only collect personal information that you submit to us.</Text>

                    <Space h="lg" />

                    <Text size="30px">How Do We Use Your Email Address?</Text>
                    <Text>
                        By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party.
                        We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order.
                        If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
                    </Text>

                    <Space h="lg" />

                    <Text size="30px">How Long Do We Keep Your Information?</Text>
                    <Text>We keep your information only so long as we need it to provide [NAME] to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.</Text>

                    <Space h="lg" />

                    <Text size="30px">How Do We Protect Your Information?</Text>
                    <Text>
                        We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential.
                        After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to [NAME] or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
                    </Text>

                    <Space h="lg" />

                    <Text size="30px">Could my information be transferred to other countries?</Text>
                    <Text>[NAME] is incorporated in Canada. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.</Text>

                    <Space h="lg" />

                    <Text size="30px">Is the information collected through the [NAME] Service secure?</Text>
                    <Text>
                        We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security.
                        If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.
                    </Text>

                    <Space h="lg" />

                    <Text size="30px">Can I update or correct my information?</Text>
                    <Text>The rights you have to request updates or corrections to the information [NAME] collects depend on your relationship with [NAME]. Personnel may update or correct their information as detailed in our internal company employment policies.</Text>
                    <Text>
                        Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.
                        To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times.
                    </Text>
                    <Text>You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.</Text>
                    <Text>If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.</Text>
                
                    <Space h="lg" />

                    <Text size="30px">Personnel</Text>
                    <Text>If you are a [NAME] worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.</Text>
                    <Text>You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.</Text>
                
                    <Space h="lg" />

                    <Text size="30px">Sale of Business</Text>
                    <Text>We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of [NAME] or any of its Corporate Affiliates (as defined herein), or that portion of [NAME] or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.</Text>

                    <Space h="lg" />

                    <Text size="30px">Affiliates</Text>
                    <Text>We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with [NAME], whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.</Text>

                    <Space h="lg" />

                    <Text size="30px">Governing Law</Text>
                    <Text>This Privacy Policy is governed by the laws of Canada, including but not limited to the Personal Information Protection and Electronic Documents Act (PIPEDA), and any applicable provincial privacy legislation, without regard to its conflict of laws provisions. You consent to the exclusive jurisdiction of the courts in Aberta in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy, except for individuals who may have rights to make claims under any applicable privacy laws or regulations.</Text>
                    <Text>The laws of Canada, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.</Text>
                    <Text>By using [NAME] or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.</Text>

                    <Space h="lg"/>

                    <Text size="30px">Your Consent</Text>
                    <Text>We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.</Text>

                    <Space h="lg"/>

                    <Text size="30px">Links to Other Websites</Text>
                    <Text>
                        This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by [NAME]. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. 
                        Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
                    </Text>

                    <Space h="lg"/>

                    <Text size="30px">Cookies</Text>
                    <Text>
                        [NAME] uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. 
                        Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
                    </Text>

                    <Space h="lg"/>

                    <Text size="30px">Blocking and disabling cookies and similar technologies</Text>
                    <Text>
                        Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. 
                        Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.
                    </Text>

                    <Space h="lg"/>
                    
                    <Text size="30px">Remarketing Services</Text>
                    <Text>We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're “following” people around the internet by serving ads on the websites and platforms they use most.</Text>

                    <Space h="lg"/>
                    
                    <Text size="30px">Payment Details</Text>
                    <Text>In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.</Text>
                
                    <Space h="lg"/>

                    <Text size="30px">Kids' Privacy</Text>
                    <Text>We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</Text>

                    <Space h="lg"/>

                    <Text size="30px">Changes To Our Privacy Policy</Text>
                    <Text>We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.</Text>

                    <Space h="lg"/>

                    <Text size="30px">Third-Party Services</Text>
                    <Text>We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").</Text>
                    <Text>You acknowledge and agree that [NAME] shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. [NAME] does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</Text>
                    <Text>Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</Text>

                    <Space h="lg"/>

                    <Text size="30px">Tracking Technologies</Text>
                    <List>
                        <List.Item>
                            Cookies
                            <Text>
                                We use Cookies to enhance the performance and functionality of our $platform but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the $platform as we would not be able to remember that you had logged in previously.
                            </Text>
                        </List.Item>
                        <List.Item>
                            Local Storage
                            <Text>Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.</Text>
                        </List.Item>
                        <List.Item>
                            Sessions
                            <Text>[NAME] uses "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.</Text>
                        </List.Item>
                        <List.Item>
                            GPS geolocation
                            <Text>With permission and if enforced by your employer we will use GPS technologies to record and track your real-time location. This feature is optional and serves to facilitate mandatory onsite time tracking for clocking in and out, ensuring compliance with company policies and regulations.</Text>
                        </List.Item>
                    </List>

                    <Space h="lg"/>

                    <Text size="30px">What is personal data?</Text>
                    <Text>Any data that relates to an identifiable or identified individual. Personal data extends beyond a person’s name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity.</Text>
                    <Text>The Data Protection Principles include requirements such as:</Text>
                    <List>
                        <List.Item>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</List.Item>
                        <List.Item>Personal data should only be collected to fulfill a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.</List.Item>
                        <List.Item>Personal data should be held no longer than necessary to fulfill its purpose.</List.Item>
                    </List>

                    <Space h="lg"/>
            
                    <Text size="30px">Individual Data Subject's Rights - Data Access, Portability and Deletion</Text>
                    <Text>We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.</Text>
                    
                    <Space h="lg"/>
                    
                    <Text size="30px">California Residents</Text>
                    <Text>The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</Text>
                    <Text>We are also required to communicate information about rights California residents have under California law. You may exercise the following rights:</Text>
                    <List>
                        <List.Item>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</List.Item>
                        <List.Item>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</List.Item>
                        <List.Item>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</List.Item>
                        <List.Item>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</List.Item>
                    </List>
                    <Text>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</Text>
                    <Text>We do not sell the Personal Information of our users.</Text>

                    <Space h="lg"/>

                    <Text size="30px">California Online Privacy Protection Act (CalOPPA)</Text>
                    <Text>CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</Text>
                    <Text>CalOPPA users have the following rights:</Text>
                    <List>
                        <List.Item>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</List.Item>
                        <List.Item>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</List.Item>
                        <List.Item>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</List.Item>
                        <List.Item>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</List.Item>
                    </List>
                    <Text>If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</Text>
                    <Text>We do not sell the Personal Information of our users.</Text>

                    <Space h="lg"/>

                    <Text size="30px">Contact Us</Text>
                    <Text>Don't hesitate to contact us if you have any questions.</Text>
                    <Text>support@website.com</Text>
                    <Text>© All rights reserved - [NAME] YYYY</Text>
                </Stack>
            </Container>
        </>
    );
}